// frontend/app/settings/page.tsx
'use client'

import { useEffect, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import CheckboxGroup from '@/components/CheckboxGroup'
import { createClient } from '@/lib/supabase/client'
import type { Source, Tag } from '@/types'
import styles from './page.module.css'

export default function SettingsPage() {
  const supabase = createClient()

  const [user, setUser] = useState<User | null>(null)
  const [sources, setSources] = useState<Source[]>([])
  const [tags, setTags] = useState<Tag[]>([])
  const [selectedSourceIds, setSelectedSourceIds] = useState<number[]>([])
  const [selectedTagIds, setSelectedTagIds] = useState<number[]>([])
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    async function init() {
      const { data: userData } = await supabase.auth.getUser()
      setUser(userData.user)

      const [sourcesResponse, tagsResponse, preferencesResponse] = await Promise.all([
        supabase.from('sources').select('id, name, website_url, category, logo_url').order('name'),
        supabase.from('tags').select('id, name').order('name'),
        supabase.from('user_preferences').select('tag_id, source_id'),
      ])

      setSources(sourcesResponse.data ?? [])
      setTags(tagsResponse.data ?? [])

      const preferences = preferencesResponse.data ?? []
      setSelectedSourceIds(preferences.filter((p) => p.source_id).map((p) => p.source_id as number))
      setSelectedTagIds(preferences.filter((p) => p.tag_id).map((p) => p.tag_id as number))
    }

    init()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function save() {
    if (!user) return
    const uid = user.id

    setSaving(true)
    setSaved(false)
    try {
      await supabase.from('user_preferences').delete().eq('user_id', uid)

      const rows = [
        ...selectedSourceIds.map((source_id) => ({ user_id: uid, source_id })),
        ...selectedTagIds.map((tag_id) => ({ user_id: uid, tag_id })),
      ]

      if (rows.length > 0) {
        await supabase.from('user_preferences').insert(rows)
      }

      setSaved(true)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <h1>Impostazioni</h1>
      <p className={styles.hint}>
        Scegli le fonti e i tag che vuoi seguire: verranno usati nella scheda &quot;I miei
        interessi&quot; del feed.
      </p>

      <CheckboxGroup items={sources} value={selectedSourceIds} onChange={setSelectedSourceIds} label="Fonti" />
      <CheckboxGroup items={tags} value={selectedTagIds} onChange={setSelectedTagIds} label="Tag" />

      <button className={styles.saveButton} disabled={saving} onClick={save}>
        {saving ? 'Salvataggio…' : 'Salva preferenze'}
      </button>
      {saved && <p className={styles.savedMessage}>Preferenze salvate.</p>}
    </div>
  )
}

// frontend/app/pages/settings.vue
<template>
  <div>
    <h1>Impostazioni</h1>
    <p class="hint">Scegli le fonti e i tag che vuoi seguire: verranno usati nella scheda "I miei interessi" del feed.</p>

    <CheckboxGroup v-model="selectedSourceIds" :items="sources" label="Fonti" />
    <CheckboxGroup v-model="selectedTagIds" :items="tags" label="Tag" />

    <button class="save-button" :disabled="saving" @click="save">
      {{ saving ? 'Salvataggio…' : 'Salva preferenze' }}
    </button>
    <p v-if="saved" class="saved-message">Preferenze salvate.</p>
  </div>
</template>

<script setup lang="ts">
import type { Source, Tag } from '~/types'

// Nessun middleware esplicito: questa pagina non è nella lista `exclude` di
// nuxt.config.ts, quindi il modulo @nuxtjs/supabase la protegge già da solo
// (redirect a /login se non autenticato).

const supabase = useSupabaseClient()
const user = useSupabaseUser()

const sources = ref<Source[]>([])
const tags = ref<Tag[]>([])
const selectedSourceIds = ref<number[]>([])
const selectedTagIds = ref<number[]>([])
const saving = ref(false)
const saved = ref(false)

onMounted(async () => {
  const [sourcesResponse, tagsResponse, preferencesResponse] = await Promise.all([
    supabase.from('sources').select('id, name, website_url, category, logo_url').order('name'),
    supabase.from('tags').select('id, name').order('name'),
    supabase.from('user_preferences').select('tag_id, source_id'),
  ])

  sources.value = sourcesResponse.data ?? []
  tags.value = tagsResponse.data ?? []

  const preferences = preferencesResponse.data ?? []
  selectedSourceIds.value = preferences.filter((p) => p.source_id).map((p) => p.source_id as number)
  selectedTagIds.value = preferences.filter((p) => p.tag_id).map((p) => p.tag_id as number)
})

async function save() {
  if (!user.value) return
  const uid = user.value.id

  saving.value = true
  saved.value = false
  try {
    await supabase.from('user_preferences').delete().eq('user_id', uid)

    const rows = [
      ...selectedSourceIds.value.map((source_id) => ({ user_id: uid, source_id })),
      ...selectedTagIds.value.map((tag_id) => ({ user_id: uid, tag_id })),
    ]

    if (rows.length > 0) {
      await supabase.from('user_preferences').insert(rows)
    }

    saved.value = true
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.hint {
  color: var(--muted-text);
}

.save-button {
  padding: 0.6rem 1.2rem;
  border-radius: 6px;
  border: none;
  background: var(--accent);
  color: white;
  cursor: pointer;
}

.save-button:disabled {
  opacity: 0.6;
  cursor: default;
}

.saved-message {
  color: var(--muted-text);
  margin-top: 0.5rem;
}
</style>
